Build fails with "error C2039: 'string': is not a member of 'std'": Moved the inclusion of the thirdparty projects to before including the project sources (so that its targets are available to the sources targets). Added the missing qcustomplot target to the export sets of the mvvm libraries.